// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Ability struct {
	Name        string `json:"name"`
	ShortEffect string `json:"shortEffect"`
	Effect      string `json:"effect"`
	Generation  string `json:"generation"`
}

type Move struct {
	Name        string `json:"name"`
	Type        string `json:"type"`
	Effect      string `json:"effect"`
	ShortEffect string `json:"shortEffect"`
	Accuracy    int    `json:"accuracy"`
	DamageClass string `json:"damageClass"`
	Generation  string `json:"generation"`
}

type Pokemon struct {
	Name                  string     `json:"name"`
	NationalPokedexNumber int        `json:"nationalPokedexNumber"`
	Types                 []string   `json:"types"`
	Stats                 []*Stats   `json:"stats"`
	Abilities             []*Ability `json:"abilities"`
	Moves                 []*Move    `json:"moves"`
	Sprites               *Sprites   `json:"sprites,omitempty"`
}

type PokemonFilter struct {
	Name                  *string `json:"name,omitempty"`
	NationalPokedexNumber *int    `json:"nationalPokedexNumber,omitempty"`
}

type PokemonsFilter struct {
	Generation *int `json:"generation,omitempty"`
}

type Sprites struct {
	BackDefault      *string `json:"backDefault,omitempty"`
	BackFemale       *string `json:"backFemale,omitempty"`
	BackShiny        *string `json:"backShiny,omitempty"`
	BackShinyFemale  *string `json:"backShinyFemale,omitempty"`
	FrontDefault     *string `json:"frontDefault,omitempty"`
	FrontFemale      *string `json:"frontFemale,omitempty"`
	FrontShiny       *string `json:"frontShiny,omitempty"`
	FrontShinyFemale *string `json:"frontShinyFemale,omitempty"`
}

type Stats struct {
	Name     string `json:"name"`
	BaseStat int    `json:"baseStat"`
	Effort   int    `json:"effort"`
}
