// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Ability struct {
	Name        string `json:"name"`
	ShortEffect string `json:"shortEffect"`
	Effect      string `json:"effect"`
	Generation  string `json:"generation"`
}

type Move struct {
	Name        string `json:"name"`
	Accuracy    int    `json:"accuracy"`
	DamageClass string `json:"damageClass"`
	Power       int    `json:"power"`
	Pp          int    `json:"pp"`
	Priority    int    `json:"priority"`
	Target      string `json:"target"`
	Type        string `json:"type"`
	Generation  string `json:"generation"`
}

type MoveVersionGroupDetails struct {
	LevelLearnedAt int    `json:"levelLearnedAt"`
	LearnMethod    string `json:"learnMethod"`
	Version        string `json:"version"`
}

type Pokemon struct {
	Name                  string                `json:"name"`
	NationalPokedexNumber int                   `json:"nationalPokedexNumber"`
	Types                 []string              `json:"types"`
	Stats                 []*Stat               `json:"stats"`
	Abilities             []*Ability            `json:"abilities"`
	Moves                 []*PokemonMoveDetails `json:"moves"`
	Sprites               *Sprites              `json:"sprites,omitempty"`
}

type PokemonFilter struct {
	Name                  *string `json:"name,omitempty"`
	NationalPokedexNumber *int    `json:"nationalPokedexNumber,omitempty"`
}

type PokemonMoveDetails struct {
	Name           string                     `json:"name"`
	VersionDetails []*MoveVersionGroupDetails `json:"versionDetails"`
}

type PokemonsFilter struct {
	Generation *int `json:"generation,omitempty"`
	Offset     *int `json:"offset,omitempty"`
}

type Sprites struct {
	BackDefault      *string `json:"backDefault,omitempty"`
	BackFemale       *string `json:"backFemale,omitempty"`
	BackShiny        *string `json:"backShiny,omitempty"`
	BackShinyFemale  *string `json:"backShinyFemale,omitempty"`
	FrontDefault     *string `json:"frontDefault,omitempty"`
	FrontFemale      *string `json:"frontFemale,omitempty"`
	FrontShiny       *string `json:"frontShiny,omitempty"`
	FrontShinyFemale *string `json:"frontShinyFemale,omitempty"`
}

type Stat struct {
	Name     string `json:"name"`
	BaseStat int    `json:"baseStat"`
	Effort   int    `json:"effort"`
}
